import type { ImageSourcePropType } from 'react-native'

/**
 * Country / territory registry for the profile location picker.
 *
 * `code` matches a flag PNG under `app/assets/shield-card/flags/flag/<CODE>.png`.
 * Metro can only bundle static `require()` paths, so every entry's asset is
 * inlined here. To add a country: add the PNG, then add one row below.
 *
 * `name` is the English display name shown in the picker. Short forms are
 * preferred over diplomatic long names (e.g. "Russia" not "Russian Federation")
 * so the list stays readable on phone widths.
 */
export type Country = {
  code: string
  name: string
  flag: ImageSourcePropType
}

export const COUNTRIES: ReadonlyArray<Country> = [
  { code: 'AC', name: 'Ascension Island', flag: require('../../assets/shield-card/flags/flag/AC.png') },
  { code: 'AD', name: 'Andorra', flag: require('../../assets/shield-card/flags/flag/AD.png') },
  { code: 'AE', name: 'United Arab Emirates', flag: require('../../assets/shield-card/flags/flag/AE.png') },
  { code: 'AF', name: 'Afghanistan', flag: require('../../assets/shield-card/flags/flag/AF.png') },
  { code: 'AG', name: 'Antigua and Barbuda', flag: require('../../assets/shield-card/flags/flag/AG.png') },
  { code: 'AI', name: 'Anguilla', flag: require('../../assets/shield-card/flags/flag/AI.png') },
  { code: 'AL', name: 'Albania', flag: require('../../assets/shield-card/flags/flag/AL.png') },
  { code: 'AM', name: 'Armenia', flag: require('../../assets/shield-card/flags/flag/AM.png') },
  { code: 'AO', name: 'Angola', flag: require('../../assets/shield-card/flags/flag/AO.png') },
  { code: 'AQ', name: 'Antarctica', flag: require('../../assets/shield-card/flags/flag/AQ.png') },
  { code: 'AR', name: 'Argentina', flag: require('../../assets/shield-card/flags/flag/AR.png') },
  { code: 'AS', name: 'American Samoa', flag: require('../../assets/shield-card/flags/flag/AS.png') },
  { code: 'AT', name: 'Austria', flag: require('../../assets/shield-card/flags/flag/AT.png') },
  { code: 'AU', name: 'Australia', flag: require('../../assets/shield-card/flags/flag/AU.png') },
  { code: 'AW', name: 'Aruba', flag: require('../../assets/shield-card/flags/flag/AW.png') },
  { code: 'AX', name: 'Åland Islands', flag: require('../../assets/shield-card/flags/flag/AX.png') },
  { code: 'AZ', name: 'Azerbaijan', flag: require('../../assets/shield-card/flags/flag/AZ.png') },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: require('../../assets/shield-card/flags/flag/BA.png') },
  { code: 'BB', name: 'Barbados', flag: require('../../assets/shield-card/flags/flag/BB.png') },
  { code: 'BD', name: 'Bangladesh', flag: require('../../assets/shield-card/flags/flag/BD.png') },
  { code: 'BE', name: 'Belgium', flag: require('../../assets/shield-card/flags/flag/BE.png') },
  { code: 'BF', name: 'Burkina Faso', flag: require('../../assets/shield-card/flags/flag/BF.png') },
  { code: 'BG', name: 'Bulgaria', flag: require('../../assets/shield-card/flags/flag/BG.png') },
  { code: 'BH', name: 'Bahrain', flag: require('../../assets/shield-card/flags/flag/BH.png') },
  { code: 'BI', name: 'Burundi', flag: require('../../assets/shield-card/flags/flag/BI.png') },
  { code: 'BJ', name: 'Benin', flag: require('../../assets/shield-card/flags/flag/BJ.png') },
  { code: 'BL', name: 'Saint Barthélemy', flag: require('../../assets/shield-card/flags/flag/BL.png') },
  { code: 'BM', name: 'Bermuda', flag: require('../../assets/shield-card/flags/flag/BM.png') },
  { code: 'BN', name: 'Brunei', flag: require('../../assets/shield-card/flags/flag/BN.png') },
  { code: 'BO', name: 'Bolivia', flag: require('../../assets/shield-card/flags/flag/BO.png') },
  { code: 'BQ', name: 'Caribbean Netherlands', flag: require('../../assets/shield-card/flags/flag/BQ.png') },
  { code: 'BR', name: 'Brazil', flag: require('../../assets/shield-card/flags/flag/BR.png') },
  { code: 'BS', name: 'Bahamas', flag: require('../../assets/shield-card/flags/flag/BS.png') },
  { code: 'BT', name: 'Bhutan', flag: require('../../assets/shield-card/flags/flag/BT.png') },
  { code: 'BV', name: 'Bouvet Island', flag: require('../../assets/shield-card/flags/flag/BV.png') },
  { code: 'BW', name: 'Botswana', flag: require('../../assets/shield-card/flags/flag/BW.png') },
  { code: 'BY', name: 'Belarus', flag: require('../../assets/shield-card/flags/flag/BY.png') },
  { code: 'BZ', name: 'Belize', flag: require('../../assets/shield-card/flags/flag/BZ.png') },
  { code: 'CA', name: 'Canada', flag: require('../../assets/shield-card/flags/flag/CA.png') },
  { code: 'CC', name: 'Cocos (Keeling) Islands', flag: require('../../assets/shield-card/flags/flag/CC.png') },
  { code: 'CD', name: 'DR Congo', flag: require('../../assets/shield-card/flags/flag/CD.png') },
  { code: 'CF', name: 'Central African Republic', flag: require('../../assets/shield-card/flags/flag/CF.png') },
  { code: 'CG', name: 'Republic of the Congo', flag: require('../../assets/shield-card/flags/flag/CG.png') },
  { code: 'CH', name: 'Switzerland', flag: require('../../assets/shield-card/flags/flag/CH.png') },
  { code: 'CI', name: 'Côte d’Ivoire', flag: require('../../assets/shield-card/flags/flag/CI.png') },
  { code: 'CK', name: 'Cook Islands', flag: require('../../assets/shield-card/flags/flag/CK.png') },
  { code: 'CL', name: 'Chile', flag: require('../../assets/shield-card/flags/flag/CL.png') },
  { code: 'CM', name: 'Cameroon', flag: require('../../assets/shield-card/flags/flag/CM.png') },
  { code: 'CN', name: 'China', flag: require('../../assets/shield-card/flags/flag/CN.png') },
  { code: 'CO', name: 'Colombia', flag: require('../../assets/shield-card/flags/flag/CO.png') },
  { code: 'CR', name: 'Costa Rica', flag: require('../../assets/shield-card/flags/flag/CR.png') },
  { code: 'CU', name: 'Cuba', flag: require('../../assets/shield-card/flags/flag/CU.png') },
  { code: 'CV', name: 'Cabo Verde', flag: require('../../assets/shield-card/flags/flag/CV.png') },
  { code: 'CW', name: 'Curaçao', flag: require('../../assets/shield-card/flags/flag/CW.png') },
  { code: 'CX', name: 'Christmas Island', flag: require('../../assets/shield-card/flags/flag/CX.png') },
  { code: 'CY', name: 'Cyprus', flag: require('../../assets/shield-card/flags/flag/CY.png') },
  { code: 'CZ', name: 'Czechia', flag: require('../../assets/shield-card/flags/flag/CZ.png') },
  { code: 'DE', name: 'Germany', flag: require('../../assets/shield-card/flags/flag/DE.png') },
  { code: 'DJ', name: 'Djibouti', flag: require('../../assets/shield-card/flags/flag/DJ.png') },
  { code: 'DK', name: 'Denmark', flag: require('../../assets/shield-card/flags/flag/DK.png') },
  { code: 'DM', name: 'Dominica', flag: require('../../assets/shield-card/flags/flag/DM.png') },
  { code: 'DO', name: 'Dominican Republic', flag: require('../../assets/shield-card/flags/flag/DO.png') },
  { code: 'DZ', name: 'Algeria', flag: require('../../assets/shield-card/flags/flag/DZ.png') },
  { code: 'EC', name: 'Ecuador', flag: require('../../assets/shield-card/flags/flag/EC.png') },
  { code: 'EE', name: 'Estonia', flag: require('../../assets/shield-card/flags/flag/EE.png') },
  { code: 'EG', name: 'Egypt', flag: require('../../assets/shield-card/flags/flag/EG.png') },
  { code: 'EH', name: 'Western Sahara', flag: require('../../assets/shield-card/flags/flag/EH.png') },
  { code: 'ER', name: 'Eritrea', flag: require('../../assets/shield-card/flags/flag/ER.png') },
  { code: 'ES', name: 'Spain', flag: require('../../assets/shield-card/flags/flag/ES.png') },
  { code: 'ET', name: 'Ethiopia', flag: require('../../assets/shield-card/flags/flag/ET.png') },
  { code: 'EU', name: 'European Union', flag: require('../../assets/shield-card/flags/flag/EU.png') },
  { code: 'FI', name: 'Finland', flag: require('../../assets/shield-card/flags/flag/FI.png') },
  { code: 'FJ', name: 'Fiji', flag: require('../../assets/shield-card/flags/flag/FJ.png') },
  { code: 'FK', name: 'Falkland Islands', flag: require('../../assets/shield-card/flags/flag/FK.png') },
  { code: 'FM', name: 'Micronesia', flag: require('../../assets/shield-card/flags/flag/FM.png') },
  { code: 'FO', name: 'Faroe Islands', flag: require('../../assets/shield-card/flags/flag/FO.png') },
  { code: 'FR', name: 'France', flag: require('../../assets/shield-card/flags/flag/FR.png') },
  { code: 'GA', name: 'Gabon', flag: require('../../assets/shield-card/flags/flag/GA.png') },
  { code: 'GB', name: 'United Kingdom', flag: require('../../assets/shield-card/flags/flag/GB.png') },
  { code: 'GD', name: 'Grenada', flag: require('../../assets/shield-card/flags/flag/GD.png') },
  { code: 'GE', name: 'Georgia', flag: require('../../assets/shield-card/flags/flag/GE.png') },
  { code: 'GE-AB', name: 'Abkhazia', flag: require('../../assets/shield-card/flags/flag/GE-AB.png') },
  { code: 'GE-OS', name: 'South Ossetia', flag: require('../../assets/shield-card/flags/flag/GE-OS.png') },
  { code: 'GF', name: 'French Guiana', flag: require('../../assets/shield-card/flags/flag/GF.png') },
  { code: 'GG', name: 'Guernsey', flag: require('../../assets/shield-card/flags/flag/GG.png') },
  { code: 'GH', name: 'Ghana', flag: require('../../assets/shield-card/flags/flag/GH.png') },
  { code: 'GI', name: 'Gibraltar', flag: require('../../assets/shield-card/flags/flag/GI.png') },
  { code: 'GL', name: 'Greenland', flag: require('../../assets/shield-card/flags/flag/GL.png') },
  { code: 'GM', name: 'Gambia', flag: require('../../assets/shield-card/flags/flag/GM.png') },
  { code: 'GN', name: 'Guinea', flag: require('../../assets/shield-card/flags/flag/GN.png') },
  { code: 'GP', name: 'Guadeloupe', flag: require('../../assets/shield-card/flags/flag/GP.png') },
  { code: 'GQ', name: 'Equatorial Guinea', flag: require('../../assets/shield-card/flags/flag/GQ.png') },
  { code: 'GR', name: 'Greece', flag: require('../../assets/shield-card/flags/flag/GR.png') },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', flag: require('../../assets/shield-card/flags/flag/GS.png') },
  { code: 'GT', name: 'Guatemala', flag: require('../../assets/shield-card/flags/flag/GT.png') },
  { code: 'GU', name: 'Guam', flag: require('../../assets/shield-card/flags/flag/GU.png') },
  { code: 'GW', name: 'Guinea-Bissau', flag: require('../../assets/shield-card/flags/flag/GW.png') },
  { code: 'GY', name: 'Guyana', flag: require('../../assets/shield-card/flags/flag/GY.png') },
  { code: 'HK', name: 'Hong Kong', flag: require('../../assets/shield-card/flags/flag/HK.png') },
  { code: 'HM', name: 'Heard and McDonald Islands', flag: require('../../assets/shield-card/flags/flag/HM.png') },
  { code: 'HN', name: 'Honduras', flag: require('../../assets/shield-card/flags/flag/HN.png') },
  { code: 'HR', name: 'Croatia', flag: require('../../assets/shield-card/flags/flag/HR.png') },
  { code: 'HT', name: 'Haiti', flag: require('../../assets/shield-card/flags/flag/HT.png') },
  { code: 'HU', name: 'Hungary', flag: require('../../assets/shield-card/flags/flag/HU.png') },
  { code: 'ID', name: 'Indonesia', flag: require('../../assets/shield-card/flags/flag/ID.png') },
  { code: 'IE', name: 'Ireland', flag: require('../../assets/shield-card/flags/flag/IE.png') },
  { code: 'IL', name: 'Israel', flag: require('../../assets/shield-card/flags/flag/IL.png') },
  { code: 'IM', name: 'Isle of Man', flag: require('../../assets/shield-card/flags/flag/IM.png') },
  { code: 'IN', name: 'India', flag: require('../../assets/shield-card/flags/flag/IN.png') },
  { code: 'IO', name: 'British Indian Ocean Territory', flag: require('../../assets/shield-card/flags/flag/IO.png') },
  { code: 'IQ', name: 'Iraq', flag: require('../../assets/shield-card/flags/flag/IQ.png') },
  { code: 'IR', name: 'Iran', flag: require('../../assets/shield-card/flags/flag/IR.png') },
  { code: 'IS', name: 'Iceland', flag: require('../../assets/shield-card/flags/flag/IS.png') },
  { code: 'IT', name: 'Italy', flag: require('../../assets/shield-card/flags/flag/IT.png') },
  { code: 'JE', name: 'Jersey', flag: require('../../assets/shield-card/flags/flag/JE.png') },
  { code: 'JM', name: 'Jamaica', flag: require('../../assets/shield-card/flags/flag/JM.png') },
  { code: 'JO', name: 'Jordan', flag: require('../../assets/shield-card/flags/flag/JO.png') },
  { code: 'JP', name: 'Japan', flag: require('../../assets/shield-card/flags/flag/JP.png') },
  { code: 'KE', name: 'Kenya', flag: require('../../assets/shield-card/flags/flag/KE.png') },
  { code: 'KG', name: 'Kyrgyzstan', flag: require('../../assets/shield-card/flags/flag/KG.png') },
  { code: 'KH', name: 'Cambodia', flag: require('../../assets/shield-card/flags/flag/KH.png') },
  { code: 'KI', name: 'Kiribati', flag: require('../../assets/shield-card/flags/flag/KI.png') },
  { code: 'KM', name: 'Comoros', flag: require('../../assets/shield-card/flags/flag/KM.png') },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: require('../../assets/shield-card/flags/flag/KN.png') },
  { code: 'KP', name: 'North Korea', flag: require('../../assets/shield-card/flags/flag/KP.png') },
  { code: 'KR', name: 'South Korea', flag: require('../../assets/shield-card/flags/flag/KR.png') },
  { code: 'KW', name: 'Kuwait', flag: require('../../assets/shield-card/flags/flag/KW.png') },
  { code: 'KY', name: 'Cayman Islands', flag: require('../../assets/shield-card/flags/flag/KY.png') },
  { code: 'KZ', name: 'Kazakhstan', flag: require('../../assets/shield-card/flags/flag/KZ.png') },
  { code: 'LA', name: 'Laos', flag: require('../../assets/shield-card/flags/flag/LA.png') },
  { code: 'LB', name: 'Lebanon', flag: require('../../assets/shield-card/flags/flag/LB.png') },
  { code: 'LC', name: 'Saint Lucia', flag: require('../../assets/shield-card/flags/flag/LC.png') },
  { code: 'LI', name: 'Liechtenstein', flag: require('../../assets/shield-card/flags/flag/LI.png') },
  { code: 'LK', name: 'Sri Lanka', flag: require('../../assets/shield-card/flags/flag/LK.png') },
  { code: 'LR', name: 'Liberia', flag: require('../../assets/shield-card/flags/flag/LR.png') },
  { code: 'LS', name: 'Lesotho', flag: require('../../assets/shield-card/flags/flag/LS.png') },
  { code: 'LT', name: 'Lithuania', flag: require('../../assets/shield-card/flags/flag/LT.png') },
  { code: 'LU', name: 'Luxembourg', flag: require('../../assets/shield-card/flags/flag/LU.png') },
  { code: 'LV', name: 'Latvia', flag: require('../../assets/shield-card/flags/flag/LV.png') },
  { code: 'LY', name: 'Libya', flag: require('../../assets/shield-card/flags/flag/LY.png') },
  { code: 'MA', name: 'Morocco', flag: require('../../assets/shield-card/flags/flag/MA.png') },
  { code: 'MC', name: 'Monaco', flag: require('../../assets/shield-card/flags/flag/MC.png') },
  { code: 'MD', name: 'Moldova', flag: require('../../assets/shield-card/flags/flag/MD.png') },
  { code: 'ME', name: 'Montenegro', flag: require('../../assets/shield-card/flags/flag/ME.png') },
  { code: 'MF', name: 'Saint Martin', flag: require('../../assets/shield-card/flags/flag/MF.png') },
  { code: 'MG', name: 'Madagascar', flag: require('../../assets/shield-card/flags/flag/MG.png') },
  { code: 'MH', name: 'Marshall Islands', flag: require('../../assets/shield-card/flags/flag/MH.png') },
  { code: 'MK', name: 'North Macedonia', flag: require('../../assets/shield-card/flags/flag/MK.png') },
  { code: 'ML', name: 'Mali', flag: require('../../assets/shield-card/flags/flag/ML.png') },
  { code: 'MM', name: 'Myanmar', flag: require('../../assets/shield-card/flags/flag/MM.png') },
  { code: 'MN', name: 'Mongolia', flag: require('../../assets/shield-card/flags/flag/MN.png') },
  { code: 'MO', name: 'Macao', flag: require('../../assets/shield-card/flags/flag/MO.png') },
  { code: 'MP', name: 'Northern Mariana Islands', flag: require('../../assets/shield-card/flags/flag/MP.png') },
  { code: 'MQ', name: 'Martinique', flag: require('../../assets/shield-card/flags/flag/MQ.png') },
  { code: 'MR', name: 'Mauritania', flag: require('../../assets/shield-card/flags/flag/MR.png') },
  { code: 'MS', name: 'Montserrat', flag: require('../../assets/shield-card/flags/flag/MS.png') },
  { code: 'MT', name: 'Malta', flag: require('../../assets/shield-card/flags/flag/MT.png') },
  { code: 'MU', name: 'Mauritius', flag: require('../../assets/shield-card/flags/flag/MU.png') },
  { code: 'MV', name: 'Maldives', flag: require('../../assets/shield-card/flags/flag/MV.png') },
  { code: 'MW', name: 'Malawi', flag: require('../../assets/shield-card/flags/flag/MW.png') },
  { code: 'MX', name: 'Mexico', flag: require('../../assets/shield-card/flags/flag/MX.png') },
  { code: 'MY', name: 'Malaysia', flag: require('../../assets/shield-card/flags/flag/MY.png') },
  { code: 'MZ', name: 'Mozambique', flag: require('../../assets/shield-card/flags/flag/MZ.png') },
  { code: 'NA', name: 'Namibia', flag: require('../../assets/shield-card/flags/flag/NA.png') },
  { code: 'NC', name: 'New Caledonia', flag: require('../../assets/shield-card/flags/flag/NC.png') },
  { code: 'NE', name: 'Niger', flag: require('../../assets/shield-card/flags/flag/NE.png') },
  { code: 'NF', name: 'Norfolk Island', flag: require('../../assets/shield-card/flags/flag/NF.png') },
  { code: 'NG', name: 'Nigeria', flag: require('../../assets/shield-card/flags/flag/NG.png') },
  { code: 'NI', name: 'Nicaragua', flag: require('../../assets/shield-card/flags/flag/NI.png') },
  { code: 'NL', name: 'Netherlands', flag: require('../../assets/shield-card/flags/flag/NL.png') },
  { code: 'NO', name: 'Norway', flag: require('../../assets/shield-card/flags/flag/NO.png') },
  { code: 'NP', name: 'Nepal', flag: require('../../assets/shield-card/flags/flag/NP.png') },
  { code: 'NR', name: 'Nauru', flag: require('../../assets/shield-card/flags/flag/NR.png') },
  { code: 'NU', name: 'Niue', flag: require('../../assets/shield-card/flags/flag/NU.png') },
  { code: 'NZ', name: 'New Zealand', flag: require('../../assets/shield-card/flags/flag/NZ.png') },
  { code: 'OM', name: 'Oman', flag: require('../../assets/shield-card/flags/flag/OM.png') },
  { code: 'PA', name: 'Panama', flag: require('../../assets/shield-card/flags/flag/PA.png') },
  { code: 'PE', name: 'Peru', flag: require('../../assets/shield-card/flags/flag/PE.png') },
  { code: 'PF', name: 'French Polynesia', flag: require('../../assets/shield-card/flags/flag/PF.png') },
  { code: 'PG', name: 'Papua New Guinea', flag: require('../../assets/shield-card/flags/flag/PG.png') },
  { code: 'PH', name: 'Philippines', flag: require('../../assets/shield-card/flags/flag/PH.png') },
  { code: 'PK', name: 'Pakistan', flag: require('../../assets/shield-card/flags/flag/PK.png') },
  { code: 'PL', name: 'Poland', flag: require('../../assets/shield-card/flags/flag/PL.png') },
  { code: 'PM', name: 'Saint Pierre and Miquelon', flag: require('../../assets/shield-card/flags/flag/PM.png') },
  { code: 'PN', name: 'Pitcairn Islands', flag: require('../../assets/shield-card/flags/flag/PN.png') },
  { code: 'PR', name: 'Puerto Rico', flag: require('../../assets/shield-card/flags/flag/PR.png') },
  { code: 'PS', name: 'Palestine', flag: require('../../assets/shield-card/flags/flag/PS.png') },
  { code: 'PT', name: 'Portugal', flag: require('../../assets/shield-card/flags/flag/PT.png') },
  { code: 'PW', name: 'Palau', flag: require('../../assets/shield-card/flags/flag/PW.png') },
  { code: 'PY', name: 'Paraguay', flag: require('../../assets/shield-card/flags/flag/PY.png') },
  { code: 'QA', name: 'Qatar', flag: require('../../assets/shield-card/flags/flag/QA.png') },
  { code: 'RE', name: 'Réunion', flag: require('../../assets/shield-card/flags/flag/RE.png') },
  { code: 'RO', name: 'Romania', flag: require('../../assets/shield-card/flags/flag/RO.png') },
  { code: 'RS', name: 'Serbia', flag: require('../../assets/shield-card/flags/flag/RS.png') },
  { code: 'RU', name: 'Russia', flag: require('../../assets/shield-card/flags/flag/RU.png') },
  { code: 'RW', name: 'Rwanda', flag: require('../../assets/shield-card/flags/flag/RW.png') },
  { code: 'SA', name: 'Saudi Arabia', flag: require('../../assets/shield-card/flags/flag/SA.png') },
  { code: 'SB', name: 'Solomon Islands', flag: require('../../assets/shield-card/flags/flag/SB.png') },
  { code: 'SC', name: 'Seychelles', flag: require('../../assets/shield-card/flags/flag/SC.png') },
  { code: 'SD', name: 'Sudan', flag: require('../../assets/shield-card/flags/flag/SD.png') },
  { code: 'SE', name: 'Sweden', flag: require('../../assets/shield-card/flags/flag/SE.png') },
  { code: 'SG', name: 'Singapore', flag: require('../../assets/shield-card/flags/flag/SG.png') },
  { code: 'SH', name: 'Saint Helena', flag: require('../../assets/shield-card/flags/flag/SH.png') },
  { code: 'SI', name: 'Slovenia', flag: require('../../assets/shield-card/flags/flag/SI.png') },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', flag: require('../../assets/shield-card/flags/flag/SJ.png') },
  { code: 'SK', name: 'Slovakia', flag: require('../../assets/shield-card/flags/flag/SK.png') },
  { code: 'SL', name: 'Sierra Leone', flag: require('../../assets/shield-card/flags/flag/SL.png') },
  { code: 'SM', name: 'San Marino', flag: require('../../assets/shield-card/flags/flag/SM.png') },
  { code: 'SN', name: 'Senegal', flag: require('../../assets/shield-card/flags/flag/SN.png') },
  { code: 'SO', name: 'Somalia', flag: require('../../assets/shield-card/flags/flag/SO.png') },
  { code: 'SR', name: 'Suriname', flag: require('../../assets/shield-card/flags/flag/SR.png') },
  { code: 'SS', name: 'South Sudan', flag: require('../../assets/shield-card/flags/flag/SS.png') },
  { code: 'ST', name: 'São Tomé and Príncipe', flag: require('../../assets/shield-card/flags/flag/ST.png') },
  { code: 'SV', name: 'El Salvador', flag: require('../../assets/shield-card/flags/flag/SV.png') },
  { code: 'SX', name: 'Sint Maarten', flag: require('../../assets/shield-card/flags/flag/SX.png') },
  { code: 'SY', name: 'Syria', flag: require('../../assets/shield-card/flags/flag/SY.png') },
  { code: 'SZ', name: 'Eswatini', flag: require('../../assets/shield-card/flags/flag/SZ.png') },
  { code: 'TA', name: 'Tristan da Cunha', flag: require('../../assets/shield-card/flags/flag/TA.png') },
  { code: 'TC', name: 'Turks and Caicos Islands', flag: require('../../assets/shield-card/flags/flag/TC.png') },
  { code: 'TD', name: 'Chad', flag: require('../../assets/shield-card/flags/flag/TD.png') },
  { code: 'TF', name: 'French Southern Territories', flag: require('../../assets/shield-card/flags/flag/TF.png') },
  { code: 'TG', name: 'Togo', flag: require('../../assets/shield-card/flags/flag/TG.png') },
  { code: 'TH', name: 'Thailand', flag: require('../../assets/shield-card/flags/flag/TH.png') },
  { code: 'TJ', name: 'Tajikistan', flag: require('../../assets/shield-card/flags/flag/TJ.png') },
  { code: 'TK', name: 'Tokelau', flag: require('../../assets/shield-card/flags/flag/TK.png') },
  { code: 'TL', name: 'Timor-Leste', flag: require('../../assets/shield-card/flags/flag/TL.png') },
  { code: 'TM', name: 'Turkmenistan', flag: require('../../assets/shield-card/flags/flag/TM.png') },
  { code: 'TN', name: 'Tunisia', flag: require('../../assets/shield-card/flags/flag/TN.png') },
  { code: 'TO', name: 'Tonga', flag: require('../../assets/shield-card/flags/flag/TO.png') },
  { code: 'TR', name: 'Turkey', flag: require('../../assets/shield-card/flags/flag/TR.png') },
  { code: 'TT', name: 'Trinidad and Tobago', flag: require('../../assets/shield-card/flags/flag/TT.png') },
  { code: 'TV', name: 'Tuvalu', flag: require('../../assets/shield-card/flags/flag/TV.png') },
  { code: 'TW', name: 'Taiwan', flag: require('../../assets/shield-card/flags/flag/TW.png') },
  { code: 'TZ', name: 'Tanzania', flag: require('../../assets/shield-card/flags/flag/TZ.png') },
  { code: 'UA', name: 'Ukraine', flag: require('../../assets/shield-card/flags/flag/UA.png') },
  { code: 'UG', name: 'Uganda', flag: require('../../assets/shield-card/flags/flag/UG.png') },
  { code: 'UM', name: 'U.S. Minor Outlying Islands', flag: require('../../assets/shield-card/flags/flag/UM.png') },
  { code: 'US', name: 'United States', flag: require('../../assets/shield-card/flags/flag/US.png') },
  { code: 'UY', name: 'Uruguay', flag: require('../../assets/shield-card/flags/flag/UY.png') },
  { code: 'UZ', name: 'Uzbekistan', flag: require('../../assets/shield-card/flags/flag/UZ.png') },
  { code: 'VA', name: 'Vatican City', flag: require('../../assets/shield-card/flags/flag/VA.png') },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: require('../../assets/shield-card/flags/flag/VC.png') },
  { code: 'VE', name: 'Venezuela', flag: require('../../assets/shield-card/flags/flag/VE.png') },
  { code: 'VG', name: 'British Virgin Islands', flag: require('../../assets/shield-card/flags/flag/VG.png') },
  { code: 'VI', name: 'U.S. Virgin Islands', flag: require('../../assets/shield-card/flags/flag/VI.png') },
  { code: 'VN', name: 'Vietnam', flag: require('../../assets/shield-card/flags/flag/VN.png') },
  { code: 'VU', name: 'Vanuatu', flag: require('../../assets/shield-card/flags/flag/VU.png') },
  { code: 'WF', name: 'Wallis and Futuna', flag: require('../../assets/shield-card/flags/flag/WF.png') },
  { code: 'WS', name: 'Samoa', flag: require('../../assets/shield-card/flags/flag/WS.png') },
  { code: 'XK', name: 'Kosovo', flag: require('../../assets/shield-card/flags/flag/XK.png') },
  { code: 'YE', name: 'Yemen', flag: require('../../assets/shield-card/flags/flag/YE.png') },
  { code: 'YT', name: 'Mayotte', flag: require('../../assets/shield-card/flags/flag/YT.png') },
  { code: 'ZA', name: 'South Africa', flag: require('../../assets/shield-card/flags/flag/ZA.png') },
  { code: 'ZM', name: 'Zambia', flag: require('../../assets/shield-card/flags/flag/ZM.png') },
  { code: 'ZW', name: 'Zimbabwe', flag: require('../../assets/shield-card/flags/flag/ZW.png') },
] as const

const COUNTRIES_BY_NAME = new Map(COUNTRIES.map((c) => [c.name.toLowerCase(), c]))
const COUNTRIES_BY_CODE = new Map(COUNTRIES.map((c) => [c.code.toUpperCase(), c]))

/**
 * Resolve a stored `areaLocation` string back to a `Country` row.
 * Accepts either the country name (e.g. `"South Africa"`) or the country code
 * (e.g. `"ZA"`). Returns `null` if no match (e.g. legacy free-text entries).
 */
export function findCountry(value: string | null | undefined): Country | null {
  if (!value) return null
  const trimmed = value.trim()
  if (!trimmed) return null
  const byName = COUNTRIES_BY_NAME.get(trimmed.toLowerCase())
  if (byName) return byName
  const byCode = COUNTRIES_BY_CODE.get(trimmed.toUpperCase())
  if (byCode) return byCode
  return null
}
